"""update message

Revision ID: bb895de53356
Revises: 
Create Date: 2025-03-28 19:03:04.925011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb895de53356'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messageimage')
    op.create_unique_constraint(None, 'conversation', ['id'])
    op.add_column('message', sa.Column('files', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'message', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'message', type_='unique')
    op.drop_column('message', 'files')
    op.drop_constraint(None, 'conversation', type_='unique')
    op.create_table('messageimage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='messageimage_message_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messageimage_pkey')
    )
    # ### end Alembic commands ###
